//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApexDBEFApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public CLIENTES()
        {
            this.PEDIDOS = new HashSet<PEDIDOS>();
        }
    
        public int ID { get; set; }
        public string NOME { get; set; }
        public string ENDERECO { get; set; }
        public string CIDADE { get; set; }
        public Nullable<System.DateTime> DATA_NASCIMENTO { get; set; }
    
        public virtual ICollection<PEDIDOS> PEDIDOS { get; set; }
    }
}
